### ISSUE TITLE
Contribute this to the official Realm Xcode plugin?

### ISSUE THREAD

**Issue by jpsim** [kittinunf/RealmBrowser-Plugin#1]
Nice work! :+1:

We'd love to have this functionality as part of the official Realm Xcode plugin. We added the ability to open the browser from Xcode a few months ago (https://github.com/realm/realm-cocoa/pull/922) but never added functionality to open a relevant file.

So we'd be happy to consider a PR if you wanted to contribute this back "upstream". Sorry if this is more of a suggestion than an issue :stuck_out_tongue:.

**Comment by kittinunf** [comment]
Oh, thanks. I don't see any reason why this is not a good idea. I did not know that Realm plugin was able to open the browser too (as it is advertised as more towards a "file template" plugin on Alcatraz). 

Then, yes. The only logical way going forward is to having one nice Realm Browser plugin, not 2. I am more than happy to contribute back.

Kindly let me how this works. :dancers:

**Comment by jpsim** [comment]
You could file a PR towards https://github.com/realm/realm-cocoa, the plugin is in the `plugin/` directory of the repo.

**Comment by kittinunf** [comment]
Ok. That is pretty straightforward. If you are not in rush, let me find some time to wrap this back to Realm official repo. As my hands are a bit full this week.

**Comment by jpsim** [comment]
No problem, thanks for building this!

**Comment by kittinunf** [comment]
It has been merged in upstream so issue is now closed.
